### ISSUE TITLE
Unable to include lazysodium using maven

### ISSUE THREAD

**Issue by GitMoDu** [terl/lazysodium-android#1]
> Could not find com.goterl.lazycode:lazysodium-android:1.1.1

I followed the "extensive" instructions of copy pasting 3 lines and can't seem to compile when I add Lazysodium to an Android project.

**Comment by gurpreet-** [comment]
Hello! Many thanks for trying out the library!

Are you using maven or gradle? Your title says maven but your adding it to an Android app which 99% build using Gradle. Not to worry, I'll add instructions for both build tools anyway.


### Maven
If you're using Maven then you have to setup a custom repo like so:

```xml
<project>
...
  <repositories>
    <repository>
      <id>lazysodium-maven-repo</id>
      <name>lazysodium-maven</name>
      <url>https://dl.bintray.com/terl/lazysodium-maven</url>
    </repository>
  </repositories>
...
</project>
```

Then, add as a dependency like so:

```xml
    <dependency>
        <groupId>com.goterl.lazycode</groupId>
        <artifactId>lazysodium-android</artifactId>
        <version>1.1.3</version>
        <type>aar</type>
    </dependency>
```

### Gradle

Add the following block to your top level gradle file (i.e. the one that's at the root of your project).

```
allprojects {
    repositories {
        // Add this block here
        maven {
            url  "https://dl.bintray.com/terl/lazysodium-maven"
        }
    }
}
```

Then add this to your app level gradle file:

```
implementation "net.java.dev.jna:jna:4.5.1@aar"
implementation "com.goterl.lazycode:lazysodium-android:1.1.3@aar"
```

Then perform a gradle clean and build.

```sh
$ gradle clean
$ gradle commandToRebuildProject
```

Let me know if that works for you 🙂

**Comment by GitMoDu** [comment]
Yes, I meant using gradle, by including the maven repository.

I found the mistake, I was adding the dependency on the build script. not the app dependencies.

Small note, on the readme it says I should use layzsodium 1.1.1.

**Comment by gurpreet-** [comment]
Okay glad you got it sorted.

Yep, that version number in the readme auto-updates if I create a new release of Lazysodium. Keep checking up on it; from time to time I may add more functions. 👍 

If you have any more problems / questions then don't hesitate to create a new issue.
