### ISSUE TITLE
Encrypt/Decrypt without nonce

### ISSUE THREAD

**Issue by yleyvag** [terl/lazysodium-android#11]
There's any way I can use lazysodium with asymetric encryption without handling the anoying nonces? It's called Authenticated Encryption.

**Comment by gurpreet-** [comment]
I don't believe there is a way to use authenticated encryption without a nonce. Lazysodium could generate the nonce for you but people may want to provide their own method of generating randomised nonces, so therefore Lazysodium doesn't handle them. 

If it's any reconciliation, you can store the nonce in a public place. Or even alongside the encrypted text separated by a delimiter like `#` for example.
