### ISSUE TITLE
Fatal signal 11 (SIGSEGV) when calling cryptoAuthHMacSha512256

### ISSUE THREAD

**Issue by cherryasphalt** [terl/lazysodium-android#16]
When using `cryptoAuthHMACSha512256` (as well as the other SHA2 HMAC methods) I receive a `Fatal signal 11 (SIGSEGV)`. Does it have to do with the signature using `int` instead of `long` for the message length? `cryptoAuth` works fine.

**Comment by gurpreet-** [comment]
Hi @turtlekiosk,

Thanks for reporting this! I think it is indeed due to cryptoAuth having `int`s instead of `long`s. I have fixed this in [`3.6.0`](https://github.com/terl/lazysodium-android/releases/tag/3.6.0).

Please let me know if it works 👍

**Comment by gurpreet-** [comment]
I'll take your silence to mean it's been fixed 😄 Closing.
