### ISSUE TITLE
Error with Random Bytes

### ISSUE THREAD

**Issue by schott12521** [terl/lazysodium-android#2]
I think the bytes buffer for signing a message is too long:

`byte[] signedMessage = randomBytesBuf(Sign.BYTES + messageBytes.length);`

means that the sign message will be of length Sign.BYTES (64) + len(message) which should not be true, the message signature should just be the length of the sign. The bytes after the first 128 of the returned signed message seem.

EG, I try to sign "1111" with a secret key, the returned message will be "(128 chars of signature)(the original message in hexadecimal)" which does not seem ideal.

Again, we discussed on reddit, but I am looking for this functionality out of this library: https://github.com/nebyark/libsodium/commit/57fe2dcc1320c0f888801e2ebd76bb2a84fa6b00

**Comment by schott12521** [comment]
This is my bad -- I'm used to just using crypto_sign_detached and getting only the signature back, I guess I can try to add that functionality in? Thanks!

**Comment by gurpreet-** [comment]
No worries my dude.

Here's the full list of what's [implemented](https://github.com/terl/lazysodium-java/tree/master/src/main/java/com/goterl/lazycode/lazysodium/interfaces).

By the way, I moved the Sign functionality to [Sign.java](https://github.com/terl/lazysodium-java/blob/master/src/main/java/com/goterl/lazycode/lazysodium/interfaces/Sign.java) as it was, in my opinion, a different operation to the other `cryptoBox*` functions.

If you want, you can do it no problem. Though I'm planning on getting the rest of the detached functions in by tonight, so you can also wait it out 🙂

**Comment by schott12521** [comment]
So it seems like my friend that wrote the functions for libsodium did them in a separate fork off of the main libsodium repo. Is there a way that I can use his forked version of libsodium with LazySodium? I'm currently looking through to see if this is possible, but im sure the creator might have an idea or two as well 👍 ! And I agree, moving the Sign functions to Sign.java makes the most sense to me.

**Comment by gurpreet-** [comment]
Oh adding new native functions can definitely be done with Lazysodium.

I just need to document how. As this is now turning into mainly a documentation issue, I've created a new issue for it at terl/lazysodium-java#18.

See you there!

**Comment by gurpreet-** [comment]
Hey @schott12521,

If Lazysodium has helped you out, place consider donating. Even $1/£1/€1 goes a long way. It'll help us to keep improving Lazysodium and hopefully branch out to more languages. More info is available by pressing the button below.

<a href="https://www.patreon.com/bePatron?u=11667122"><img src="https://filedn.com/lssh2fV92SE8dRT5CWJvvSy/patron_button.png" width="140" /></a>

Thanks!
