### ISSUE TITLE
sealedbox unavailable?

### ISSUE THREAD

**Issue by bmbariah** [terl/lazysodium-android#23]
How can I achieve the sealedBox with this lib?
[Sealed Box](https://pynacl.readthedocs.io/en/stable/public/#nacl-public-sealedbox)

I can see a function in the lazysodium lib called cryptoBoxSeal
but it returns a boolean. 
Kindly assist.
````java 
boolean signed = box.cryptoBoxSeal(ct, message.getBytes(), message.length(), publicKey);```

**Comment by gurpreet-** [comment]
Hi @bmbariah,

I am pretty sure that `SealedBox` is just [`cryptoBox*`](https://download.libsodium.org/doc/public-key_cryptography/authenticated_encryption#combined-mode) in Java.

Does that help?

**Comment by bmbariah** [comment]
Can you provide an example like the python variant they have on the website?

**Comment by bmbariah** [comment]
Hi @gurpreet- any updates on this?

**Comment by gurpreet-** [comment]
Hi @bmbariah,

Yep, so to do the equivalent in Android/Java:

```java
private LazySodiumAndroid ls;
private Box.Lazy box;
private KeyPair bobKeyPair;
private KeyPair keyPair;

public void encrypt() {
   ls = new LazySodiumAndroid(new SodiumAndroid());
   // This is our keypair.
   keyPair = box.cryptoBoxKeypair();
   // This is bob's keypair.
   bobKeyPair = box.cryptoBoxKeypair();

   // We're sending a message to Bob so
   // let's encrypt using his public key and our private key.
   KeyPair kp1 = new KeyPair(bobKeyPair.getPublicKey(), keyPair.getSecretKey());
   
   byte[] nonce = ls.randomBytesBuf(SecretBox.NONCEBYTES);

   try {
       // Encrypt the message
       String cipherText = box.cryptoBoxEasy("A super secret message", nonce, kp1);

        // Send cipherText and nonce to Bob...

       // Now Bob can decrypt it
       KeyPair kp2 = new KeyPair(keyPair.getPublicKey(), bobKeyPair.getSecretKey());
       String decrypted = lazySodium.cryptoBoxOpenEasy(cipherText, nonce, kp2);
      

     } catch (SodiumException e) {
            e.printStackTrace();
     }
}
```

The full Android example can be found [here](https://github.com/terl/lazysodium-examples/blob/master/android/app/src/main/java/com/goterl/lazycode/lazysodium/example/activities/AsymmetricEncryptionActivity.java), which is part of the Lazysodium Android Example app that can be downloaded [here](https://play.google.com/store/apps/details?id=com.goterl.lazycode.lazysodium.example). 

You can also [view](https://github.com/terl/lazysodium-java/tree/master/src/test/java/com/goterl/lazycode/lazysodium) easy to follow tests that you can gain some inspiration from. Even more examples can be found [here](https://github.com/terl/lazysodium-examples/blob/master/java/src/main/java/com/goterl/lazycode/Main.java).

Like I say, if you follow the docs of Libsodium then knowing which method to use becomes a piece of cake.

**Comment by bmbariah** [comment]
Hi @gurpreet- I don't think you got my problem..The one you posted above is how to do an openBox. Fairly easy to do, but which allows the sender to be able decrypt the messages with the nonce and their key.

What am looking for is the sealedBox functionality, where even the sender **CANNOT** decrypt information that they just encrypted. Quoting the pyNacl documentation:

> By design, the recipient will have no means to trace the ciphertext to a known author, since the sending keypair itself is not bound to any sender’s identity, and the sender herself will not be able to decrypt the ciphertext she just created, since the private part of the key cannot be recovered after use.

Here is the link to the documentation [Sealed Box](https://pynacl.readthedocs.io/en/stable/public/#nacl-public-sealedbox)
It works perfectly on python but trying to replicate the same on Android, simply doesn't work.

**Comment by gurpreet-** [comment]
Hi @bmbariah,

Sorry my bad, I did try and understand the documentation but I thought it was describing `openBox` however now I see that it has different functionality.

Do you have the corresponding python source code that performs a sealed box? I have not done python in years but I can read it and probably translate the same functionality into lazysodium.

**Comment by bmbariah** [comment]
Here is sample python code for the documentation. Tested it on my end and works great

````python
import nacl.utils
from nacl.public import PrivateKey, SealedBox

# Generate Bob's private key, as we've done in the Box example
skbob = PrivateKey.generate()
pkbob = skbob.public_key

# Alice wishes to send a encrypted message to Bob,
# but prefers the message to be untraceable
sealed_box = SealedBox(pkbob)

# This is Alice's message
message = b"Kill all kittens"

# Encrypt the message, it will carry the ephemeral key public part
# to let Bob decrypt it
encrypted = sealed_box.encrypt(message)

#Bob's decryption
#Now, Bob wants to read the secret message he just received; therefore he must create a SealedBox using his own private key:

unseal_box = SealedBox(skbob)
# decrypt the received message
plaintext = unseal_box.decrypt(encrypted)`
print(plaintext.decode('utf-8'))

**Comment by gurpreet-** [comment]
Hi @bmbariah,

Sorry for the long delay in writing.

The functionality you seek is available. Please see [`cryptoBoxSeal`](https://github.com/terl/lazysodium-java/blob/b1d3fefb1507cf0edeb36e5e5f1d73838f35056f/src/main/java/com/goterl/lazycode/lazysodium/LazySodium.java#L779).

Usage of it is similar to the procedure that I commented above. Instantiate a Lazysodium object, then use `lazysodium.cryptoBoxSeal`.

**Comment by bmbariah** [comment]
Can you provide a working sample code for Android/Java?

**Comment by gurpreet-** [comment]
Yeah sure...

```java
public class Main {

    public static void main(String[] args) throws SodiumException {
        LazySodiumJava ls = new LazySodiumJava(new SodiumJava());

        // This is bob's keypair.
        KeyPair bobKp = ls.cryptoBoxKeypair();

        // Alice wishes to send an encrypted message to Bob.
        // Even she can't decrypt it.
        byte[] message = "A super secret message".getBytes();
        byte[] cipherText = new byte[message.length + Box.SEALBYTES];
        ls.cryptoBoxSeal(cipherText, message, message.length, bobKp.getPublicKey().getAsBytes());

        // Bob can decrypt the message
        byte[] decrypted = new byte[message.length];
        boolean res = ls.cryptoBoxSealOpen(decrypted,
                cipherText,
                cipherText.length,
                bobKp.getPublicKey().getAsBytes(),
                bobKp.getSecretKey().getAsBytes());

        if (!res) {
            System.out.println("Error trying to decrypt. Maybe the message was intended for another recipient?");
        }

        System.out.println(new String(decrypted)); // Should print out "A super secret message"
    }
}
```

Full documentation can be found in [Libsodium's docs](https://libsodium.gitbook.io/doc/public-key_cryptography/sealed_boxes), which as you can see, is 99% similar to the above Lazysodium code.

**Comment by di0n0s** [comment]
Hi,

What can I do if I don't have the original message length?

Thanks.

**Comment by gurpreet-** [comment]
Hi @di0n0s, 

You can still find the original message length:`cipherMessageLength - Box.SEALBYTES` = `messageLength`
