### ISSUE TITLE
f-droid

### ISSUE THREAD

**Issue by mwarning** [terl/lazysodium-android#24]
It would be nice to have this on https://f-droid.org/ as well. A public repository for FOSS apps.

The package repository: https://gitlab.com/fdroid/fdroiddata/tree/master

**Comment by mwarning** [comment]
Ok, I prepared a package description: https://gitlab.com/mwarning/fdroiddata/commit/5413a7ea87728297d247783ef8427213a81ef616

**Comment by gurpreet-** [comment]
Het @mwarning,

This is great! Do I need to do anything else or is it in the process of being uploaded to FDroid now?

**Comment by mwarning** [comment]
I only wait for the go to submit the PR.

Btw., I tried to compile the app with android studio and failed. Is there something special I have to do?

**Comment by mwarning** [comment]
Done, I hope the system there can compile the source code: https://gitlab.com/fdroid/fdroiddata/merge_requests/5025

**Comment by mwarning** [comment]
@gurpreet-  There are some problems checking for new versions: https://github.com/terl/lazysodium-android/blob/3.7.1/app/build.gradle#L38 maybe you have an idea.

**Comment by mwarning** [comment]
There is a problem: https://gitlab.com/fdroid/fdroiddata/merge_requests/5025#note_189929254

**Comment by gurpreet-** [comment]
Hi @mwarning,

I will take a look, no promises I can fix it though 🙂

**Comment by gurpreet-** [comment]
Hi FDroid demands I build the native libraries from source. I think building those native libraries (libsodium.so, libsodium.dll) for each platform (Windows32, Windows64, MacOS, Linux, RPi, there could be more in the future!) from source is a very large challenge and too much effort to implement for a sample app. I should provide direct APK links instead.
