### ISSUE TITLE
Documentation Links

### ISSUE THREAD

**Issue by bmoliveira** [terl/lazysodium-android#26]
I was looking into the README.md and some documentation links weren't working. 

I've created a [Pull Request](https://github.com/terl/lazysodium-android/pull/25) with the updated links.

Do the links change often?

Thanks and keep up with the good work!!!

**Comment by gurpreet-** [comment]
@bmoliveira 

Awesome! Thanks! No they don't. I just had a bit of re-ordering going on and forgot to update links. Silly me!
