### ISSUE TITLE
Unable to include lazysodium using gradle

### ISSUE THREAD

**Issue by Kolisium** [terl/lazysodium-android#27]
i'm trying to include using:

> compile 'net.java.dev.jna:jna:5.3.1'
> compile 'com.goterl.lazycode:lazysodium-android:3.7.1'

OR

> compile 'net.java.dev.jna:jna:5.3.1@aar'
> compile 'com.goterl.lazycode:lazysodium-android:3.7.1@aar'

that returns:

> ERROR: Failed to resolve: com.goterl.lazycode:lazysodium-android:3.7.1

**Comment by gurpreet-** [comment]
Hi @Kolisium,

Have you added the repository `lazysodium-maven` to your top level build file as per the install instructions? https://docs.lazycode.co/lazysodium/usage/installation#android

**Comment by Kolisium** [comment]
Hi @gurpreet- ,
yes, I added the repository but it still doesn't work

**Comment by gurpreet-** [comment]
Awesome!
