### ISSUE TITLE
No implementation found for crypto_secretbox_xsalsa20poly1305_*

### ISSUE THREAD

**Issue by bsElyes** [terl/lazysodium-android#30]
Hey,

We migrated our project to use LazySodium but we got a trouble to decrypt old data encrypted with joshjdevl/libsodium-jni "crypto_secretbox_xsalsa20poly1305"  and i could not find the "crypto_secretbox_xsalsa20poly1305_open" implementation :/ and now am 
stuck , if there is a way to decrypt I will be very grateful

best regards

**Comment by gurpreet-** [comment]
Hi @bsElyes,

I'll add this ASAP and push out a release soon.

Thank you for reporting 👍

**Comment by gurpreet-** [comment]
Hi @bsElyes,

Just had a look and:  

1. `crypto_secretbox` is equal to `crypto_secretbox_xsalsa20poly1305`
2. `crypto_secretbox_open` is equal to `crypto_secretbox_xsalsa20poly1305_open`
3. `crypto_secretbox_keygen` is equal to `crypto_secretbox_xsalsa20poly1305_keygen`

You can see what each functions calls on [this](https://github.com/jedisct1/libsodium/blob/927dfe8e2eaa86160d3ba12a7e3258fbc322909c/src/libsodium/crypto_secretbox/crypto_secretbox.c) page.

This means everything is already implemented and you can start using Lazysodium straight away if you wish 😁 I will be exposing those functions anyway.
