### ISSUE TITLE
Version Naming

### ISSUE THREAD

**Issue by chrisjenx** [terl/lazysodium-android#34]
Thanks for the Lib it's really helpful and can't thank you enough.

Quick tip for naming https://semver.org/

Bumping the patch version by one should NOT contain breaking changes. That should really be a major, maybe minor version change, most devs will bump patch versions without changing because its _assumed_ it's bug fixes.

**Comment by gurpreet-** [comment]
@chrisjenx whoops I hold my hand up to this one! I wanted to keep as close to Lazysodium Java as possible. Looks like that will not be possible as Android != Java in a lot of cases!

Noted for the future!

**Comment by chrisjenx** [comment]
Hey, no worries. I get it. We all run into this - we have some odd naming at work too - kinda wish they taught standards at school/college then we would all be on the same page :)
