### ISSUE TITLE
What is the benefit of converting to Hex and not keeping it the same as native Sodium?

### ISSUE THREAD

**Issue by KarimFikani** [terl/lazysodium-android#36]
I saw it in the comment and so is in the code but I don't understand the reason behind the conversion? 

"The reason for this is that the Lazy interface defaults to converting everything to hexadecimal whereas the Native interface assumes everything is non-hexadecimal"

Is there a benefit? Wouldn't the conversion add unnecessary overhead?

**Comment by gurpreet-** [comment]
Hi @KarimFikani,

The benefit of encoding is that you can store the encoded string safely in a database or anywhere. It is truly lazy. Unfortunately, yes, extra overhead would be added but I imagine this would be insignificant. Without encoding the byte array you are at risk of doing something risky to the byte array. 

Plus, it is good to have a consistent encoding strategy throughout your project so Lazysodium stuck to hex encoding as its default. There was a `MessageEncoder` interface added to Lazysodium Android 4.1.1 so you can write your own encoder if you want https://github.com/terl/lazysodium-java/pull/70/files (Base64, Base32, etc)

**Comment by KarimFikani** [comment]
ok thx!
