### ISSUE TITLE
Possible future issue of using this repository?

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [terl/lazysodium-android#43]
I've read that they are being closed on May:

https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

As this repository says we should use jcenter in build.gradle file, doesn't it mean we should use something else ?
How can we solve this?

I actually have these:

```
allprojects {
    repositories {
        google()
        jcenter()
        maven { url 'https://dl.bintray.com/kotlin/kotlin-eap' }
        maven { url "https://jitpack.io" }
        maven { url "https://dl.bintray.com/terl/lazysodium-maven" }
    }
}
```

And in dependencies:

```
    implementation "com.goterl.lazycode:lazysodium-android:4.3.2@aar"
    implementation 'net.java.dev.jna:jna:5.6.0@aar'
```

**Comment by gurpreet-** [comment]
Hi thanks for this, I'll discuss it here: terl/lazysodium-java#94

**Comment by AndroidDeveloperLB** [comment]
Oh I didn't notice it's by the same person.

**Comment by gurpreet-** [comment]
[Release 5.0.0](https://github.com/terl/lazysodium-android/releases/tag/5.0.0) is now on MavenCentral rather than jCenter/Bintray. Instructions can be found in the readme. 

Happy coding 💻

**Comment by dani-digital** [comment]
@gurpreet- I just ran over this issue on a project of our customer (within a third-party sdk). Since they're still relying on an older version of lazysodium-android (4.2.0) and bintray.com was shutdown, are there any plans on publishing those older versions on MavenCentral? Many thanks.

**Comment by gurpreet-** [comment]
@dani-digital It's advised to upgrade to the latest release. The details for doing so can be found here https://github.com/terl/lazysodium-java/wiki/Upgrading. There's not much work required.
