### ISSUE TITLE
Lazysodium-android was removed from Google Play.

### ISSUE THREAD

**Issue by CensorKao** [terl/lazysodium-android#49]
We plan to use this project on Google play store, but lazysodium-android was removed from Google play store by Google. Can you please check and fixed it.

**Comment by gurpreet-** [comment]
Hi @CensorKao what are you referring to? The Lazysodium sample app? https://play.google.com/store/apps/details?id=com.goterl.lazycode.lazysodium.example

Looks like it has been removed 😭 but it's OK as that was a sample app that showed everything that Lazysodium can do and developers should not use it directly.

Lazysodium is a library not an app.

**Comment by CensorKao** [comment]
Our App was removed from google play store due to the advice and network abuse policy. Google tell us we have all the responsibility for what we integrated sdk now. So now we were very carefully when we using third party sdk. I just want to know why the sample was removed from Google Play. Is that the lazysodium-android matters or just the sample doesn't meet Google play's policy?

**Comment by gurpreet-** [comment]
It was probably removed due to me not updating it in a while!

**Comment by gurpreet-** [comment]
Looks like I needed to update the target audience but haven't done so. It has nothing to do with network abuse.

<img width="762" alt="removal" src="https://user-images.githubusercontent.com/6073488/120890803-e0dde100-c5fc-11eb-855e-5087bc3a5b91.png">

**Comment by CensorKao** [comment]
> Looks like I needed to update the target audience but haven't done so. It has nothing to do with network abuse.
> 
> 
> 
> <img width="762" alt="removal" src="https://user-images.githubusercontent.com/6073488/120890803-e0dde100-c5fc-11eb-855e-5087bc3a5b91.png">
> 
> 

Thanks. You should keep the sample on Google Play store. Google was very strictly on third party sdk.
