### ISSUE TITLE
unable to dissolve dependency 

### ISSUE THREAD

**Issue by Felixcity35** [terl/lazysodium-android#50]
lazy sodium was working very well, just wanted to make some few update on my code only to notice that some dependencies cant be dissolve...:

Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve com.goterl.lazycode:lazysodium-android:5.0.2.
Show Details
Affected Modules: app

i try to rebuild the project only to get this error :

Could not GET 'http://dl.bintray.com/terl/lazysodium-maven/com/goterl/lazycode/lazysodium-android/5.0.2/lazysodium-android-5.0.2.pom'. Received status code 403 from server: Forbidden

**Comment by darrynhoskingluna** [comment]
Got the same problem for a different version

**Comment by mobielbekeken-thijs** [comment]
This library was moved from bintray to mavenCentral. Please check the installation instructions again.

**Comment by gurpreet-** [comment]
Yes, as a result of bintray closing down, I had moved this to MavenCentral.

Simply add `mavenCentral()` to your `repositories` block.
