### ISSUE TITLE
How to import the library

### ISSUE THREAD

**Issue by yujiri8** [terl/lazysodium-android#56]
I wrote a project that uses the Java version of this library, worked, and now need to switch it to the android version.

I have followed exactly the android instructions here:
https://github.com/terl/lazysodium-java/wiki/installation

But am now getting errors that the package com.goterl.lazysodium.* doesn't exist.

I've looked at the sample app but don't see where the dependency is declared.

**Comment by gurpreet-** [comment]
Can I confirm what is written in the dependencies block for your Java and Android projects respectively?

As of this comment's writing, here's the latest of what you should have for Java:

```
dependencies {
    implementation "com.goterl:lazysodium-java:5.1.4"
    implementation "net.java.dev.jna:jna:5.12.1"
}
```

And for Android:


```
dependencies {
    implementation "com.goterl:lazysodium-android:5.1.0@aar"
    implementation "net.java.dev.jna:jna:5.12.1@aar"
}
```

**Comment by yujiri8** [comment]
It has been a long time and I eventually solved this issue, but forgot to update this issue. I have this in a Java library that uses it:
```
	api "com.goterl:lazysodium-java:5.1.0"
```

And this in an Android app that uses my library:
```
dependencies {
    implementation 'com.goterl:lazysodium-android:5.0.2@aar'
    implementation 'net.java.dev.jna:jna:5.11.0@aar'
}
```
