### ISSUE TITLE
Crash when calling `new LazySodiumAndroid(new SodiumAndroid());`

### ISSUE THREAD

**Issue by susanp** [terl/lazysodium-android#9]
When I try to use your library I get the following error when running my Android app:

`java.lang.NoClassDefFoundError: Failed resolution of: Lcom/sun/jna/Native;
at com.goterl.lazycode.lazysodium.SodiumAndroid.<init>(SodiumAndroid.java:37)
at com.goterl.lazycode.lazysodium.SodiumAndroid.<init>(SodiumAndroid.java:17)`

Any idea on how to fix this? It compiles without problems, but on runtime it crashes when calling `LazySodiumAndroid lazySodium = new LazySodiumAndroid(new SodiumAndroid());`.

**Comment by gurpreet-** [comment]
Hello @susanp.

Whoops! I seem to have forgotten to add instructions to include JNA as a dependency in the docs. Totally my bad.

I think adding this line to the dependencies will resolve your error:

```groovy
dependencies {
    implementation "com.goterl.lazycode:lazysodium-android:VERSION_NUMBER@aar"
    implementation 'net.java.dev.jna:jna:4.5.1@aar' // Add this line
}
```

Let me know if that works for you. I'll add the missing JNA dependency instructions to the readme and docs soon. Thanks.

**Comment by gurpreet-** [comment]
Added to docs and the readme. Thanks for the report!

**Comment by karan4c6** [comment]
I have also faced the same issue and I could find fix over here only after googling. 
The fix is still not in the documentation or Readme file:
implementation 'net.java.dev.jna:jna:4.5.1@aar' // Add this line

Kindly add it to readme.
Thanks
